credit_text = [
"SUNRISE",
"Creator & Director - WushR00M",
"Creator - UndergroundError",
" ",
"PROGRAMMING",
"Lead Program - WushR00M",
"Programming - TheBlueVolcano",
"Assistant Programming - SimonDoes",
"Development Tools - Julian (Juju) Adams",
" ",
"ART & DESIGN",
"Lead Artist - WushR00M",
"Character, Prop, and BG Art - Rose&Theo",
"Character Design - Obvlixx",
"Character Design - UndergroundError",
"Concept Design - TheBlueVolcano",
"Guest Artist - Jason Lee (jasontomlee)",
" ",
"VOICE TALENT",
"Announcer Guy - Miles Laughability",
"Goodbye Voices:",
"- WushR00M",
"- TheBlueVolcano",
"- H4949",
"- S&WProductions (ess)",
"- XawoWasTaken",
" ",
"MUSIC",
"Lead Musicican - WushR00M",
"Musician - Caystel",
"Musician - SpeheeSphereDude",
"Musician - UndergroundError",
"Guest Musician - sulflix",
"Guest Musician - Derpcat",
"Guest Musician - solare",
" ",
"SOUNDS",
"Sound Design - WushR00M",
"Sound Design - XawoWasTaken",
"Various Sounds - Freesound",
" ",
"QA",
"Design QA - Obvlixx",
"Design QA - TheBlueVolcano",
"Design QA - SimonDoes",
"Design QA - Lampshade",
"Design & Music QA - Rose&Theo",
" ",
// "KICKSTARTER SUPPORTERS",
// "Backer - Username",
// " ",
"(C) WushR00M Studios 2021 - 2025. All rights reserved.",
"Sunrise: Alpha v0.3",
"DEVELOPMENTAL BUILD, NOTHING HERE IS FINAL! (maybe)",

];

scroll_y = display_get_height(); // Starts below the screen
line_height = 32;
scroll_speed = 1;

audio_play_sound(mus_a_millenium_to_a_dream, 0, true);